### ISSUE TITLE
Using a 2D scene

### ISSUE THREAD

**Issue by lullinglore** [gagdiez/PACgd#3]
Hi there!
First of all, I was very surprised to see a new point-n-click framework -- I'm preparing for a very serious game (as in, not as a hobby) and was determined to make my own after trying out Escoria and being disappointed by its overly complicated system (mainly because it's trying to be as customizable as possible)...

This one looks much simpler and straightforward to use! Thank you for making this!

Now, onto the issue, which is more of a question really: can't we use this framework with only 2D nodes? I assume most users won't want anything to do with 3D either.
If not, is there a workaround (I'm not afraid to fiddle around with the code a little to adapt it to my needs)?

**Comment by gagdiez** [comment]
Hi @Lulullia,

Thank you for getting interested in this project! Indeed, this project was born after trying to use Escoria and realizing how complicated it is.

I think you made a good suggestion, so I implemented the 2D version of PACgd. The new nodes are: `Character2D`, `Interactive2D`, and `Floor2D`. I [made a simple example here](https://github.com/gagdiez/PACgd_examples/tree/main/2DGame) on how to use them.

I did not update the documentation, simply because all the same principles apply. This is, anything that you see being done with a `Interactive` node can be replicated exactly with a `Interactive2D` node.

Please fill free to try the new version and let me know what you think.

If you have any further questions do not hesitate on opening another issue, or reaching me on discord (gagdiez#6744)

Best,
gagdiez

**Comment by lullinglore** [comment]
That was fast! It works great, thanks for implementing this.
In the end I'm still making my own framework since my project has special needs (it's not just a point-n-click), but your implementation will definitely be helpful for handling the point-n-click part.

I look forward for the next releases, and possibly more collaboration!

**Comment by gagdiez** [comment]
@Lulullia  Sure, no problem. If you need help with the implementation let me know. Also, if you want to consider other frameworks you could check [RenJS](https://renjs.net/), it is perfect for making point-and-click and visual novels, and it is based on Javascript, which makes it super simple to use.

Good luck with your project!
