### ISSUE TITLE
Godot 4 version in the works?

### ISSUE THREAD

**Issue by metanoder** [gagdiez/PACgd#5]
Hi gagdiez,

Firstly, your Point and Click system is amazing!  Easy to use, and dynamic with its utilization of 3d environments. 

Don't see another way to ask this question.
With Godot 4 finally released, 
was wondering if a port to Godot 4 was on the roadmap?...

Also, would it be hard to adapt this to a fully 3d point and click?
Where the character is a fully 3d animated character, and still utilizing your system?

**Comment by gagdiez** [comment]
Hi @metanoder , thank you for your kind words. You can find the version for Godot 4.0 in the `godot-4.0` branch! For now, I will leave it there, and keep as `main` the 3.5 version, since 3.5 is LTS, and Godot 4.0 is quite experimental. Let me know if it works for you, and if you find any bugs so I can fix them.

I have no experience with 3D animations, but I suspect it should be fairly similar to the 2D animations. I will take a look at it and learn on the way.

**Comment by metanoder** [comment]
AMAZING!  Thank you for sharing this phenomenal plug in.  I love how the Godot 3 version works!  
With 3d graphics being really good for Godot 4, leveraging 3d characters along with your plug in would be so cool.   

With that being said, that does not in any take away the fact that 
having an easy to use, slick point and click plugin for Godot is PHENOMENAL in it of itself.  
THANK YOU!
